
server:
  port: 666

  ssl:
    enabled: true

    key-store: classpath:keystore.p12
    key-store-type: PKCS12

    key-store-password: 123456789
    key-alias: tomcat



grpc:
  server:
    port: 6666

    security:
      enabled: true
      certificateChain: classpath:server.crt
      privateKey: classpath:server.key

receiver:
  datasource:
    pom:

      url: jdbc:postgresql://localhost:5434/pom_db
      username: pom
      password: postgres

      driver-class-name: org.postgresql.Driver

    gru:
      url: jdbc:oracle:thin:@localhost:1521/XEPDB1
      username: GRU
      password: gru_password

      driver-class-name: oracle.jdbc.OracleDriver

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true


scheduler:
  scan:
    frequency: 10000

  cleanup:
    start: "0 0 2 * * ?"
    lifespan: 30



app:
  filespaths:
    process-dir: D:/job/FoodCards/incoming
    target-dir: D:/job/FoodCards

