CREATE SEQUENCE IF NOT EXISTS pom_file_seq
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE


CREATE SEQUENCE IF NOT EXISTS pom_unit_seq
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE


CREATE SEQUENCE IF NOT EXISTS pom_unit_error_seq
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE


